---

- name: check monit version
  shell: |
    monit -V | sed -n 's/This is Monit version //p'
  register: monit_sys_version
  ignore_errors: yes
  changed_when: false
  
- include: install.yml
  when:
    monit_sys_version.stdout != monit_version

- name: Create required directories
  file:
    dest: '{{ item.dest }}'
    mode: '{{ item.mode | default("0700") }}'
    owner: '{{ item.owner | default("root") }}'
    group: '{{ item.group | default("root") }}'
    state: '{{ item.state | default("directory") }}'
  with_items:
    - dest: /etc/monitrc.d
    - dest: /etc/monitrc.d/services
    - dest: /etc/monitrc.d/scripts
    - dest: /etc/monitrc.d/templates
    - dest: '{{ monit_var_dir }}'

- name: Install monit upstart script
  copy:
    src: etc/init/monit.conf
    dest: /etc/init/monit.conf
    
- name: install default monit configuration
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest | default("/" + item.src) }}'
    mode: '{{ item.mode | default("0600") }}'
    owner: '{{ item.owner | default("root") }}'
    group: '{{ item.group | default("root") }}'
  notify: monit restart
  with_items:
    - src: etc/monitrc.d/passwd
    - src: etc/monitrc

- name: install monit base checks
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest | default("/" + item.src) }}'
    mode: '{{ item.mode | default("0600") }}'
    owner: '{{ item.owner | default("root") }}'
    group: '{{ item.group | default("root") }}'
  notify: monit restart
  with_items:
    - src: etc/monitrc.d/templates/rootbin
    - src: etc/monitrc.d/templates/rootrc
    - src: etc/monitrc.d/templates/rootstrict
    - src: etc/monitrc.d/services/ssh.cfg
    - src: etc/monitrc.d/services/cron.cfg
